CREATE TABLE incidents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_key CHAR(64) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    external_fingerprint VARCHAR(255) NULL,
    alert_name VARCHAR(255) NOT NULL,
    service_id BIGINT UNSIGNED NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    probe_type VARCHAR(20) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    status ENUM('firing','acknowledged','processing','resolved','closed') NOT NULL,
    summary VARCHAR(512) NOT NULL,
    description TEXT NOT NULL,
    fired_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    resolved_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    acknowledged_at DATETIME(3) NULL,
    processing_at DATETIME(3) NULL,
    acknowledged_by BIGINT UNSIGNED NULL,
    processing_by BIGINT UNSIGNED NULL,
    closed_by BIGINT UNSIGNED NULL,
    occurrence_count BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_incidents_event_key (event_key),
    KEY idx_incidents_status_updated (status, updated_at),
    KEY idx_incidents_fingerprint_fired (fingerprint, fired_at),
    CONSTRAINT fk_incidents_ack_user FOREIGN KEY (acknowledged_by) REFERENCES users(id),
    CONSTRAINT fk_incidents_processing_user FOREIGN KEY (processing_by) REFERENCES users(id),
    CONSTRAINT fk_incidents_closed_user FOREIGN KEY (closed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

