CREATE TABLE probe_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    service_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    interval_seconds INT UNSIGNED NOT NULL,
    timeout_milliseconds INT UNSIGNED NOT NULL,
    max_retries TINYINT UNSIGNED NOT NULL,
    retry_base_delay_milliseconds INT UNSIGNED NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    next_run_at DATETIME(3) NOT NULL,
    last_scheduled_at DATETIME(3) NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_probe_tasks_service_name (service_id, name),
    KEY idx_probe_tasks_due (status, next_run_at, id),
    CONSTRAINT fk_probe_tasks_service FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT fk_probe_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_probe_tasks_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE probe_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    execution_id CHAR(32) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    service_id BIGINT UNSIGNED NOT NULL,
    probe_type ENUM('http', 'tcp') NOT NULL,
    target_snapshot VARCHAR(2048) NOT NULL,
    scheduled_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    duration_milliseconds BIGINT UNSIGNED NULL,
    status ENUM('queued', 'running', 'succeeded', 'failed') NOT NULL,
    success BOOLEAN NULL,
    attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    http_status_code INT NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1024) NULL,
    worker_consumer VARCHAR(255) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_probe_results_execution (execution_id),
    KEY idx_probe_results_task_created (task_id, created_at),
    KEY idx_probe_results_service_created (service_id, created_at),
    KEY idx_probe_results_queued (status, scheduled_at),
    CONSTRAINT fk_probe_results_task FOREIGN KEY (task_id) REFERENCES probe_tasks(id),
    CONSTRAINT fk_probe_results_service FOREIGN KEY (service_id) REFERENCES services(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

