#!/usr/bin/env bash

# Install the checksum-verified External Secrets Operator bundle generated by
# the mirror-external-secrets-image GitHub Actions workflow. The script does
# not create registry credentials, source Secrets, SecretStores, Argo CD, or
# any CloudSentinel workload.

set -Eeuo pipefail

readonly EXPECTED_VERSION="v2.8.0"
readonly EXPECTED_UPSTREAM_SHA256="7d1533a7ace1f0ee9a21ac2215665e8f5856690ca7b224961df2011ff735d572"
readonly EXPECTED_IMAGE_ROOT="crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-external-secrets"
readonly EXPECTED_NAMESPACE="external-secrets"
readonly EXPECTED_PULL_SECRET="platform-acr-registry"
readonly SCRIPT_REVISION="2026-08-14.1"

apply=false
bundle_dir=""
log_file=""
rendered_file=""

usage() {
	cat <<'EOF'
Usage:
  bash install-external-secrets.sh \
    --bundle-dir /root/external-secrets-v2.8.0 \
    --apply

Run this script as root on master-01 after:
  1. downloading the external-secrets-v2.8.0-linux-amd64 Actions artifact;
  2. uploading the extracted bundle directory to master-01;
  3. creating external-secrets/platform-acr-registry from a protected
     .dockerconfigjson file.

This script installs only External Secrets Operator. It does not create source
Secrets, SecretStores, Argo CD, PersistentVolumes, or CloudSentinel workloads.
EOF
}

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

section() {
	printf '\n===== %s =====\n' "$1"
}

on_exit() {
	local exit_code=$?
	if [[ -n "${rendered_file}" && -f "${rendered_file}" ]]; then
		rm -f -- "${rendered_file}"
	fi
	if [[ "${exit_code}" -eq 0 ]]; then
		printf '\nEXTERNAL_SECRETS_INSTALL_RESULT=PASS\n'
	else
		printf '\nEXTERNAL_SECRETS_INSTALL_RESULT=FAIL exit_code=%s\n' \
			"${exit_code}" >&2
	fi
	if [[ -n "${log_file}" ]]; then
		printf 'EXTERNAL_SECRETS_INSTALL_LOG=%s\n' "${log_file}"
	fi
}

trap on_exit EXIT

while (($# > 0)); do
	case "$1" in
	--apply)
		apply=true
		shift
		;;
	--bundle-dir)
		(($# >= 2)) || die "--bundle-dir requires a value"
		bundle_dir="$2"
		shift 2
		;;
	--help | -h)
		usage
		exit 0
		;;
	*)
		usage >&2
		die "unknown argument: $1"
		;;
	esac
done

[[ "${apply}" == "true" ]] || {
	usage
	die "no changes made; pass --apply to approve the installation"
}
[[ "${EUID}" -eq 0 ]] || die "run this script as root"
[[ "$(hostname -s)" == "master-01" ]] || die "this script must run on master-01"
[[ -n "${bundle_dir}" ]] || die "--bundle-dir is required"
[[ "${bundle_dir}" = /* ]] || die "--bundle-dir must be an absolute path"
[[ -d "${bundle_dir}" ]] || die "bundle directory does not exist: ${bundle_dir}"

export KUBECONFIG="${KUBECONFIG:-/etc/kubernetes/admin.conf}"
[[ -r "${KUBECONFIG}" ]] || die "kubeconfig is not readable: ${KUBECONFIG}"

log_file="/root/cloudsentinel-external-secrets-install-$(date +%Y%m%dT%H%M%S).log"
exec > >(tee -a "${log_file}") 2>&1

section "execution boundary"
printf 'script_revision=%s\n' "${SCRIPT_REVISION}"
printf 'bundle_dir=%s\n' "${bundle_dir}"
printf 'kubeconfig=%s\n' "${KUBECONFIG}"
printf 'This script will not create or print Secret values.\n'

section "bundle integrity"
readonly -a required_files=(
	"external-secrets.upstream.yaml"
	"external-secrets.namespaced.yaml"
	"namespace.yaml"
	"kustomization.yaml"
	"metadata.env"
	"external-secrets.rendered.yaml"
	"checksums.sha256"
)
for required_file in "${required_files[@]}"; do
	[[ -f "${bundle_dir}/${required_file}" ]] ||
		die "bundle file is missing: ${required_file}"
done
(
	cd "${bundle_dir}"
	sha256sum --check --strict checksums.sha256
)

actual_upstream_sha="$(sha256sum \
	"${bundle_dir}/external-secrets.upstream.yaml" | awk '{print $1}')"
[[ "${actual_upstream_sha}" == "${EXPECTED_UPSTREAM_SHA256}" ]] ||
	die "official manifest checksum does not match the approved release"

grep -Fxq "EXTERNAL_SECRETS_VERSION=${EXPECTED_VERSION}" \
	"${bundle_dir}/metadata.env" || die "bundle version is not approved"
grep -Fxq "UPSTREAM_MANIFEST_SHA256=${EXPECTED_UPSTREAM_SHA256}" \
	"${bundle_dir}/metadata.env" || die "bundle metadata checksum is not approved"
metadata_deploy_image="$(grep -E '^DEPLOY_IMAGE=' \
	"${bundle_dir}/metadata.env" | cut -d= -f2-)"
metadata_digest="${metadata_deploy_image#"${EXPECTED_IMAGE_ROOT}@"}"
[[ "${metadata_deploy_image}" == "${EXPECTED_IMAGE_ROOT}@${metadata_digest}" ]] ||
	die "bundle metadata uses an unapproved registry repository"
[[ "${metadata_digest}" =~ ^sha256:[0-9a-f]{64}$ ]] ||
	die "bundle metadata does not contain an immutable digest"

section "cluster preflight"
command -v kubectl >/dev/null 2>&1 || die "kubectl is not installed"
context="$(kubectl config current-context)"
printf 'context=%s\n' "${context}"
kubectl get --raw='/readyz' | grep -Fxq ok || die "API server is not ready"

node_count="$(kubectl get nodes --no-headers | wc -l)"
ready_count="$(kubectl get nodes --no-headers |
	awk '$2 == "Ready" {count++} END {print count+0}')"
[[ "${node_count}" -eq 7 && "${ready_count}" -eq 7 ]] ||
	die "expected 7 Ready Kubernetes nodes, got ${ready_count}/${node_count}"

app_node_count="$(kubectl get nodes -l node-role=app --no-headers | wc -l)"
[[ "${app_node_count}" -eq 2 ]] ||
	die "expected exactly two node-role=app nodes, got ${app_node_count}"

kubectl get namespace "${EXPECTED_NAMESPACE}" >/dev/null 2>&1 ||
	die "namespace ${EXPECTED_NAMESPACE} must exist before installation"
secret_type="$(kubectl -n "${EXPECTED_NAMESPACE}" get secret \
	"${EXPECTED_PULL_SECRET}" -o jsonpath='{.type}')"
[[ "${secret_type}" == "kubernetes.io/dockerconfigjson" ]] ||
	die "${EXPECTED_NAMESPACE}/${EXPECTED_PULL_SECRET} has the wrong type"

section "render audit"
rendered_file="$(mktemp /root/external-secrets-rendered.XXXXXX.yaml)"
kubectl kustomize "${bundle_dir}" >"${rendered_file}"

deploy_image="$(grep -E '^[[:space:]]*image:' "${rendered_file}" |
	awk '{print $2}' | sort -u)"
image_digest="${deploy_image#"${EXPECTED_IMAGE_ROOT}@"}"
[[ "${deploy_image}" == "${EXPECTED_IMAGE_ROOT}@${image_digest}" ]] ||
	die "rendered image is not under the approved ACR VPC repository"
[[ "${image_digest}" =~ ^sha256:[0-9a-f]{64}$ ]] ||
	die "rendered image is not the approved ACR VPC digest"
[[ "$(grep -Fc "image: ${deploy_image}" "${rendered_file}")" -eq 3 ]] ||
	die "expected exactly three External Secrets image references"
[[ "$(grep -c 'name: platform-acr-registry' "${rendered_file}")" -eq 3 ]] ||
	die "all three Deployments must reference the private registry Secret"
[[ "$(grep -c 'node-role: app' "${rendered_file}")" -eq 3 ]] ||
	die "all three Deployments must target app nodes"
if grep -Eq '^[[:space:]]*image:[[:space:]]+(ghcr\.io|registry\.k8s\.io|docker\.io)/' \
	"${rendered_file}"; then
	die "rendered bundle contains a public registry image"
fi
printf 'rendered_image=%s\n' "${deploy_image}"
printf 'RENDER_AUDIT=PASS\n'

section "server-side apply"
kubectl apply \
	--server-side \
	--field-manager=cloudsentinel-platform-bootstrap \
	-k "${bundle_dir}"

section "rollout verification"
kubectl -n "${EXPECTED_NAMESPACE}" wait \
	--for=condition=Available \
	deployment/external-secrets \
	deployment/external-secrets-webhook \
	deployment/external-secrets-cert-controller \
	--timeout=600s

deployment_count="$(kubectl -n "${EXPECTED_NAMESPACE}" get deployment \
	--no-headers | wc -l)"
[[ "${deployment_count}" -eq 3 ]] ||
	die "expected exactly three External Secrets Deployments"

non_app_pods="$(kubectl -n "${EXPECTED_NAMESPACE}" get pods \
	-o jsonpath='{range .items[*]}{.metadata.name}{" "}{.spec.nodeName}{"\n"}{end}' |
	while read -r pod_name node_name; do
		[[ -n "${node_name}" ]] || continue
		if ! kubectl get node "${node_name}" -o jsonpath='{.metadata.labels.node-role}' |
			grep -Fxq app; then
			printf '%s %s\n' "${pod_name}" "${node_name}"
		fi
	done)"
[[ -z "${non_app_pods}" ]] ||
	die "External Secrets pods were scheduled outside app nodes: ${non_app_pods}"

kubectl get crd \
	externalsecrets.external-secrets.io \
	secretstores.external-secrets.io \
	clustersecretstores.external-secrets.io >/dev/null
kubectl -n "${EXPECTED_NAMESPACE}" get deployment,pod -o wide
printf 'EXTERNAL_SECRETS_V1_CRDS=PASS\n'
