#!/usr/bin/env bash

# Install the checksum-verified Argo CD bundle generated by the
# mirror-argocd-images GitHub Actions workflow. The script materializes only
# the ACR pull Secret through the existing ClusterSecretStore. It does not add
# a Git repository credential, create Argo CD Applications, or deploy any
# CloudSentinel workload.

set -Eeuo pipefail

readonly EXPECTED_VERSION="v3.5.0"
readonly EXPECTED_UPSTREAM_SHA256="a32bf36a437071a1f563ebf9e81c8a39fba9057c17db7d5d041afb7b6e3f4afe"
readonly EXPECTED_NAMESPACE="argocd"
readonly EXPECTED_PULL_SECRET="platform-acr-registry"
readonly EXPECTED_STORE="cloudsentinel-secret-store"
readonly EXPECTED_ARGOCD_IMAGE_ROOT="crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-argocd"
readonly EXPECTED_DEX_IMAGE_ROOT="crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-argocd-dex"
readonly EXPECTED_REDIS_IMAGE_ROOT="crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-argocd-redis"
readonly SCRIPT_REVISION="2026-08-15.2"

apply=false
bundle_dir=""
log_file=""
rendered_file=""

usage() {
	cat <<'EOF'
Usage:
  bash install-argocd.sh \
    --bundle-dir /root/argocd-v3.5.0 \
    --apply

Run this script as root on master-01 only after:
  1. mirror-argocd-images has completed successfully on source main;
  2. the argocd-v3.5.0-linux-amd64 artifact has been extracted and uploaded;
  3. ClusterSecretStore/cloudsentinel-secret-store is Ready;
  4. source Secret cloudsentinel-registry exists in the protected namespace.

This is the non-HA Argo CD topology approved for the student lab. It does not
configure Git repository credentials, expose the UI, apply bootstrap/argocd,
or deploy CloudSentinel data/application resources.
EOF
}

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

section() {
	printf '\n===== %s =====\n' "$1"
}

on_exit() {
	local exit_code=$?
	if [[ -n "${rendered_file}" && -f "${rendered_file}" ]]; then
		rm -f -- "${rendered_file}"
	fi
	if [[ "${exit_code}" -eq 0 ]]; then
		printf '\nARGOCD_INSTALL_RESULT=PASS\n'
	else
		printf '\nARGOCD_INSTALL_RESULT=FAIL exit_code=%s\n' \
			"${exit_code}" >&2
	fi
	if [[ -n "${log_file}" ]]; then
		printf 'ARGOCD_INSTALL_LOG=%s\n' "${log_file}"
	fi
}

trap on_exit EXIT

while (($# > 0)); do
	case "$1" in
	--apply)
		apply=true
		shift
		;;
	--bundle-dir)
		(($# >= 2)) || die "--bundle-dir requires a value"
		bundle_dir="$2"
		shift 2
		;;
	--help | -h)
		usage
		exit 0
		;;
	*)
		usage >&2
		die "unknown argument: $1"
		;;
	esac
done

[[ "${apply}" == "true" ]] || {
	usage
	die "no changes made; pass --apply to approve the installation"
}
[[ "${EUID}" -eq 0 ]] || die "run this script as root"
[[ "$(hostname -s)" == "master-01" ]] || die "this script must run on master-01"
[[ -n "${bundle_dir}" ]] || die "--bundle-dir is required"
[[ "${bundle_dir}" = /* ]] || die "--bundle-dir must be an absolute path"
[[ -d "${bundle_dir}" ]] || die "bundle directory does not exist: ${bundle_dir}"

export KUBECONFIG="${KUBECONFIG:-/etc/kubernetes/admin.conf}"
[[ -r "${KUBECONFIG}" ]] || die "kubeconfig is not readable: ${KUBECONFIG}"

log_file="/root/cloudsentinel-argocd-install-$(date +%Y%m%dT%H%M%S).log"
exec > >(tee -a "${log_file}") 2>&1

section "execution boundary"
printf 'script_revision=%s\n' "${SCRIPT_REVISION}"
printf 'bundle_dir=%s\n' "${bundle_dir}"
printf 'kubeconfig=%s\n' "${KUBECONFIG}"
printf 'topology=non-ha-student-lab\n'
printf 'This script will not create or print Git credentials or Secret values.\n'

section "bundle integrity"
readonly -a required_files=(
	"argocd.upstream.yaml"
	"namespace.yaml"
	"registry-external-secret.yaml"
	"kustomization.yaml"
	"metadata.env"
	"argocd.rendered.yaml"
	"checksums.sha256"
)
for required_file in "${required_files[@]}"; do
	[[ -f "${bundle_dir}/${required_file}" ]] ||
		die "bundle file is missing: ${required_file}"
done
(
	cd "${bundle_dir}"
	sha256sum --check --strict checksums.sha256
)

actual_upstream_sha="$(sha256sum \
	"${bundle_dir}/argocd.upstream.yaml" | awk '{print $1}')"
[[ "${actual_upstream_sha}" == "${EXPECTED_UPSTREAM_SHA256}" ]] ||
	die "official Argo CD manifest checksum does not match the approved release"
grep -Fxq "ARGOCD_VERSION=${EXPECTED_VERSION}" \
	"${bundle_dir}/metadata.env" || die "bundle version is not approved"
grep -Fxq "UPSTREAM_MANIFEST_SHA256=${EXPECTED_UPSTREAM_SHA256}" \
	"${bundle_dir}/metadata.env" || die "bundle metadata checksum is not approved"

validate_metadata_image() {
	local key="$1"
	local expected_root="$2"
	local value
	local digest

	value="$(grep -E "^${key}=" "${bundle_dir}/metadata.env" | cut -d= -f2-)"
	digest="${value#"${expected_root}"@}"
	[[ "${value}" == "${expected_root}@${digest}" ]] ||
		die "${key} uses an unapproved registry repository"
	[[ "${digest}" =~ ^sha256:[0-9a-f]{64}$ ]] ||
		die "${key} does not contain an immutable digest"
}

validate_metadata_image DEPLOY_ARGOCD_IMAGE "${EXPECTED_ARGOCD_IMAGE_ROOT}"
validate_metadata_image DEPLOY_DEX_IMAGE "${EXPECTED_DEX_IMAGE_ROOT}"
validate_metadata_image DEPLOY_REDIS_IMAGE "${EXPECTED_REDIS_IMAGE_ROOT}"

section "cluster preflight"
command -v kubectl >/dev/null 2>&1 || die "kubectl is not installed"
context="$(kubectl config current-context)"
printf 'context=%s\n' "${context}"
kubectl get --raw='/readyz' | grep -Fxq ok || die "API server is not ready"

node_count="$(kubectl get nodes --no-headers | wc -l)"
ready_count="$(kubectl get nodes --no-headers |
	awk '$2 == "Ready" {count++} END {print count+0}')"
[[ "${node_count}" -eq 7 && "${ready_count}" -eq 7 ]] ||
	die "expected 7 Ready Kubernetes nodes, got ${ready_count}/${node_count}"
app_node_count="$(kubectl get nodes -l node-role=app --no-headers | wc -l)"
[[ "${app_node_count}" -eq 2 ]] ||
	die "expected exactly two node-role=app nodes, got ${app_node_count}"

kubectl get crd externalsecrets.external-secrets.io >/dev/null
kubectl wait \
	--for=condition=Ready \
	"clustersecretstore/${EXPECTED_STORE}" \
	--timeout=120s

section "render audit"
rendered_file="$(mktemp /root/argocd-rendered.XXXXXX.yaml)"
kubectl kustomize "${bundle_dir}" >"${rendered_file}"

[[ "$(grep -Fc "image: ${EXPECTED_ARGOCD_IMAGE_ROOT}@sha256:" \
	"${rendered_file}")" -eq 8 ]] || die "unexpected Argo CD image count"
[[ "$(grep -Fc "image: ${EXPECTED_DEX_IMAGE_ROOT}@sha256:" \
	"${rendered_file}")" -eq 1 ]] || die "unexpected Dex image count"
[[ "$(grep -Fc "image: ${EXPECTED_REDIS_IMAGE_ROOT}@sha256:" \
	"${rendered_file}")" -eq 1 ]] || die "unexpected Redis image count"
[[ "$(grep -c '^kind: Deployment$' "${rendered_file}")" -eq 6 ]] ||
	die "expected six Argo CD Deployments"
[[ "$(grep -c '^kind: StatefulSet$' "${rendered_file}")" -eq 1 ]] ||
	die "expected one Argo CD StatefulSet"
[[ "$(grep -c 'node-role: app' "${rendered_file}")" -eq 7 ]] ||
	die "all seven Argo CD workloads must target app nodes"
for expected_parameter in \
	'controller.status.processors: "1"' \
	'controller.operation.processors: "1"' \
	'controller.kubectl.parallelism.limit: "1"' \
	'reposerver.parallelism.limit: "1"'; do
	grep -Fq "${expected_parameter}" "${rendered_file}" ||
		die "rendered bundle is missing constrained parameter: ${expected_parameter}"
done
[[ "$(grep -c 'name: platform-acr-registry' "${rendered_file}")" -eq 9 ]] ||
	die "registry pull configuration is incomplete"
if grep -Eq '^[[:space:]]*image:[[:space:]]+(quay\.io|ghcr\.io|public\.ecr\.aws|docker\.io)/' \
	"${rendered_file}"; then
	die "rendered bundle contains a public registry image"
fi
printf 'RENDER_AUDIT=PASS\n'

section "materialize registry pull Secret"
kubectl apply \
	--server-side \
	--field-manager=cloudsentinel-platform-bootstrap \
	-f "${bundle_dir}/namespace.yaml"
kubectl apply \
	--server-side \
	--field-manager=cloudsentinel-platform-bootstrap \
	-f "${bundle_dir}/registry-external-secret.yaml"
kubectl -n "${EXPECTED_NAMESPACE}" wait \
	--for=condition=Ready \
	"externalsecret/${EXPECTED_PULL_SECRET}" \
	--timeout=180s

pull_secret_type="$(kubectl -n "${EXPECTED_NAMESPACE}" get secret \
	"${EXPECTED_PULL_SECRET}" -o jsonpath='{.type}')"
[[ "${pull_secret_type}" == "kubernetes.io/dockerconfigjson" ]] ||
	die "materialized registry Secret has the wrong type"
printf 'REGISTRY_EXTERNAL_SECRET=PASS\n'

section "server-side validation"
kubectl apply \
	--server-side \
	--force-conflicts \
	--field-manager=cloudsentinel-platform-bootstrap \
	--dry-run=server \
	-k "${bundle_dir}" >/dev/null
printf 'SERVER_DRY_RUN=PASS\n'

section "server-side apply"
kubectl apply \
	--server-side \
	--force-conflicts \
	--field-manager=cloudsentinel-platform-bootstrap \
	-k "${bundle_dir}"

section "rollout verification"
readonly -a deployments=(
	argocd-applicationset-controller
	argocd-dex-server
	argocd-notifications-controller
	argocd-redis
	argocd-repo-server
	argocd-server
)
for deployment in "${deployments[@]}"; do
	kubectl -n "${EXPECTED_NAMESPACE}" rollout status \
		"deployment/${deployment}" \
		--timeout=600s
done
kubectl -n "${EXPECTED_NAMESPACE}" rollout status \
	statefulset/argocd-application-controller \
	--timeout=600s
kubectl -n "${EXPECTED_NAMESPACE}" wait \
	--for=condition=Ready \
	pod \
	--all \
	--timeout=600s

deployment_count="$(kubectl -n "${EXPECTED_NAMESPACE}" get deployment \
	--no-headers | wc -l)"
statefulset_count="$(kubectl -n "${EXPECTED_NAMESPACE}" get statefulset \
	--no-headers | wc -l)"
[[ "${deployment_count}" -eq 6 && "${statefulset_count}" -eq 1 ]] ||
	die "unexpected Argo CD workload count"

non_app_pods="$(kubectl -n "${EXPECTED_NAMESPACE}" get pods \
	-o jsonpath='{range .items[*]}{.metadata.name}{" "}{.spec.nodeName}{"\n"}{end}' |
	while read -r pod_name node_name; do
		[[ -n "${node_name}" ]] || continue
		if ! kubectl get node "${node_name}" -o jsonpath='{.metadata.labels.node-role}' |
			grep -Fxq app; then
			printf '%s %s\n' "${pod_name}" "${node_name}"
		fi
	done)"
[[ -z "${non_app_pods}" ]] ||
	die "Argo CD pods were scheduled outside app nodes: ${non_app_pods}"

runtime_images="$(kubectl -n "${EXPECTED_NAMESPACE}" get pods \
	-o jsonpath='{range .items[*]}{range .spec.initContainers[*]}{.image}{"\n"}{end}{range .spec.containers[*]}{.image}{"\n"}{end}{end}' |
	sort -u)"
if printf '%s\n' "${runtime_images}" |
	grep -Ev '^crpi-1s64ln3ptbvgkqof-vpc\.cn-beijing\.personal\.cr\.aliyuncs\.com/cloudsentinel0306/cloudsentinel-argocd(-dex|-redis)?@sha256:[0-9a-f]{64}$'; then
	die "runtime contains an image outside the approved ACR digest set"
fi

kubectl get crd \
	applications.argoproj.io \
	applicationsets.argoproj.io \
	appprojects.argoproj.io >/dev/null
kubectl -n "${EXPECTED_NAMESPACE}" get secret \
	argocd-initial-admin-secret >/dev/null
server_service_type="$(kubectl -n "${EXPECTED_NAMESPACE}" get service \
	argocd-server -o jsonpath='{.spec.type}')"
[[ "${server_service_type}" == "ClusterIP" ]] ||
	die "argocd-server must not be exposed outside the cluster"

kubectl -n "${EXPECTED_NAMESPACE}" get deployment,statefulset,pod -o wide
printf 'ARGOCD_CRDS=PASS\n'
printf 'ARGOCD_APP_NODE_PLACEMENT=PASS\n'
printf 'ARGOCD_ACR_DIGEST_RUNTIME=PASS\n'
printf 'ARGOCD_SERVER_EXPOSURE=ClusterIP\n'
